"""empty message

Revision ID: a5f051ae3053
Revises: 6dfaa0c946c2
Create Date: 2018-07-11 13:39:07.089068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f051ae3053'
down_revision = '6dfaa0c946c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('service_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'interview', 'service', ['service_id'], ['id'])
    op.drop_column('interview', 'status')
    # ### end Alembic commands ###
